const data = [
    {
        id:1,
        description:"Hello",
        shipmentID:'BTSBTSAWB5775873638419',
        senderCountry:'GHANA',
        senderCity: 'ACCRA',
        shippingDate: '2023-04-24',
        shippingTime: '00:00:00',
        contactName:'ANGELLA KIM-DESAN',
        contactAddress:'BEL SMILE',
        shippingQuantity: 1,
        productType: "GOLD CONSIGNMENT",
        totalWeight: 28,
        deliveryCountry: "UNITED STATES",
        deliveryCity: "VANCOUVER",
        deliveryDate: "2023-04-26",
        deliveryTime: "00:00:00",
        deliveryContactName:"CHRISTOPHER OETREGA",
        deliveryContactAddress:"30 Melissa Drive",
        onRouteGhana:"On Route - GHANA, ACCRA",
        onRouteGhanaTime:"02:17 pm",
        onRouteGhanaDate:"8 April, 2023",
        heldAtUK:"Held at customs - United Kingdom, LONDON",
        heldAtUKTime:"02:20 pm",
        heldAtUKDate:"10 April 2023",
        approvedUK:" Approved - United Kingdom, LONDON",
        approvedUKTime:"02:25 pm",
        approvedUKDate:"21 April, 2023",
        onRouteUK:"On Route - United Kingdom, LONDON",
        onRouteUKTime:"06:25 pm",
        onRouteUKDate:"23April, 2023",
        inWarehouseUS:"In warehouse - United States, Los Angeles, CA",
        inWarehouseUSTime:"02:25 am",
        inWarehouseUSDate:"24 April, 2023",
        heldAtUS:"Held at customs - United States, Los Angeles, CA",
        heldAtUSTime:"02:25 am",
        heldAtUSDate:"25 April 2023",
        collectionUS:"Earring Collection - United States, Los Angeles, CA",
        collectionUSTime:"04:44 pm",
        collectionUSDate:"21 June, 2023",
        approvedUS:"Approved - United States, Los Angeles, CA",
        approvedUSTime:"02:10 pm",
        approvedUSDate:"28 June, 2023",
        onRouteUS:"On Route - United States, Los Angeles, CA",
        onRouteUSTime:"02:25 pm",
        onRouteUSDate:"29 June, 2023",

    },
    {
        id:1,
        description:"Hello",
        shipmentID:'BTSBTSAWB5775873638470',
        senderCountry:'GHANA',
        senderCity: 'TAKORADI',
        shippingDate: '2023-07-24',
        shippingTime: '12:30:00',
        contactName:'DECLAN RICE',
        contactAddress:'AJUMAKO',
        shippingQuantity: 1,
        productType: "DIAMOND CONSIGNMENT",
        totalWeight: 30,
        deliveryCountry: "UNITED STATES",
        deliveryCity: "NEW YORK",
        deliveryDate: "2023-07-26",
        deliveryTime: "00:00:00",
        deliveryContactName:"MARLIN RICE JAMES",
        deliveryContactAddress:"30 Melissa Drive",
    }
    // Add more items as needed
  ];
  
  export default data;